# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f223ccb992f18a122487ca95bcc05b7a2ca780af3023b0a7b523606071bb1e1cccc3b6bffefc9eed2a33150088021c1d6b1f93dbda13497f32acdd49d8d8bd86

test:
  secret_key_base: 611eabbcdfc8b6ad0cf05a0dd87b63b84193cbfacc62e99cd527322117db48b9bfb41733634d4414a2954a20cdd0640d180367673b8f1723a70987dc168e479e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
